src/java/control/AddZadanieBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package control;

import ejb.DataBean;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import model.Czynnosc;
import model.Pracownik;
import org.primefaces.model.DualListModel;

/**
 *
 * @author Piotrek
 */
@ManagedBean(name = "addZadanie")
@ViewScoped
public class AddZadanieBean {

    private static Logger logger = Logger.getLogger(".controll.AddZadanieBean");
    
    private String Nazwa;
    private List<Czynnosc> czynnosci = new ArrayList<Czynnosc>();
    private DualListModel<Pracownik> pracownicy;
    private Date czasRozpoczecia;
    
    private String tmpczynnoscNazwa;
    private Double tmpczynnoscStawka;
    private int tmpczynnoscCzasTrwania;
    
    @EJB
    private DataBean db;

    /**
     * Creates a new instance of AddZadanieBean
     */
    public AddZadanieBean() {
    }

    public String getNazwa() {
        return Nazwa;
    }

    public void setNazwa(String Nazwa) {
        this.Nazwa = Nazwa;
    }

    public List<Czynnosc> getCzynnosci() {
        return czynnosci;
    }

    public void setCzynnosci(List<Czynnosc> czynnosci) {
        this.czynnosci = czynnosci;
    }



    public void setPracownicy(DualListModel<Pracownik> pracownicy) {
        this.pracownicy = pracownicy;
    }

    public String getTmpczynnoscNazwa() {
        return tmpczynnoscNazwa;
    }

    public void setTmpczynnoscNazwa(String tmpczynnoscNazwa) {
        this.tmpczynnoscNazwa = tmpczynnoscNazwa;
    }

    public Double getTmpczynnoscStawka() {
        return tmpczynnoscStawka;
    }

    public void setTmpczynnoscStawka(Double tmpczynnoscStawka) {
        this.tmpczynnoscStawka = tmpczynnoscStawka;
    }

    public int getTmpczynnoscCzasTrwania() {
        return tmpczynnoscCzasTrwania;
    }

    public void setTmpczynnoscCzasTrwania(int tmpczynnoscCzasTrwania) {
        this.tmpczynnoscCzasTrwania = tmpczynnoscCzasTrwania;
    }
    
    
    
    

    public Date getCzasRozpoczecia() {
        return czasRozpoczecia;
    }

    public void setCzasRozpoczecia(Date czasRozpoczecia) {
        this.czasRozpoczecia = czasRozpoczecia;
    }
    
    public void dodajZadanie() {
        db.addZadanie(this.Nazwa, this.czasRozpoczecia);
    }
    
    public void dodajZadanieKlientowi() {
        String username = FacesContext.getCurrentInstance().getExternalContext().getUserPrincipal().getName();
        db.addZadanieKlientowi(this.Nazwa,this.czasRozpoczecia,username);
    }
    

    
}

src/java/control/ControlZadanieBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package control;

import ejb.DataBean;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import model.Czynnosc;
import model.Pracownik;
import model.Zadanie;
import util.StatystykaPracownika;
import util.StatystykaSprzetu;

/**
 *
 * @author Piotrek
 */
@ManagedBean(name = "controlZadanie")
@RequestScoped
public class ControlZadanieBean {

    /**
     * Creates a new instance of ControlZadanieBean
     */
    
    private static Logger logger = Logger.getLogger(".control.ControlZadanieBean");
    
    private List<Zadanie> zadania;
    private List<Zadanie> wybraneZadania = new ArrayList<>();
    
    @EJB
    private DataBean db;
    
    public ControlZadanieBean() {
    }
    
    public List<Zadanie> getZadaniaKlienta() {
        String username = FacesContext.getCurrentInstance().getExternalContext().getUserPrincipal().getName();
        List<Zadanie> zad = db.getZadaniaKlienta(username);
        return zad;
    }

    public List<Zadanie> getZadania() {
        this.zadania = this.db.getZadania();
        return zadania;
    }
    
    public void deleteZadanie(Zadanie zadanie) {
        this.db.removeZadanie(zadanie.getId());
    }

    public void setZadania(List<Zadanie> zadania) {
        this.zadania = zadania;
    }

    public List<Zadanie> getWybraneZadania() {
        return wybraneZadania;
    }

    public void setWybraneZadania(List<Zadanie> wybraneZadania) {
        this.wybraneZadania = wybraneZadania;
    }
    
    
    
    public int czasTrwaniaZadania(Zadanie zadanie) {
        int czasTrwania = 0;
        for(Czynnosc c : zadanie.getCzynnoscList()) {
            czasTrwania+=c.getCzasTrwania();
        }
        return czasTrwania;
    }
    
    public Date dataZakonczeniaZadania(Zadanie zadanie) {
        int czasTrwania = this.czasTrwaniaZadania(zadanie);
        Calendar cal = Calendar.getInstance();
        cal.setTime(zadanie.getCzasRozpoczecia());
        cal.add(Calendar.SECOND, czasTrwania);
        Date czasZakonczenia = cal.getTime();
        return czasZakonczenia;
    }
    
    

    private double kosztPracownikow(List<Pracownik> pracownikList, int czas) {
        double ile_minut = (double)czas/(double)pracownikList.size()/60.0;
        double koszt = 0.0;
        for(Pracownik p : pracownikList) {
            koszt+=p.getStawka()*ile_minut;
        }
        return koszt;
        
    }
    
    public List<Pracownik> getPracownikList(Zadanie zadanie) {
        HashSet<Pracownik> pracownicy;
        pracownicy = new HashSet<>();
        for(Czynnosc c : zadanie.getCzynnoscList()) {
            for(Pracownik p : c.getPracownikList()) {
                pracownicy.add(p);
            }
        }
        List<Pracownik> pracownikList = new ArrayList<>(pracownicy);
        return pracownikList;
   
    }
    
    public List<StatystykaPracownika> statystykaPracownika(Zadanie z) {
        int czas = 0;
        ArrayList<StatystykaPracownika> lsp = new ArrayList<>();
        for(Pracownik p : this.getPracownikList(z)) {
            StatystykaPracownika sp = new StatystykaPracownika();
            sp.setPracownik(p);
            for(Czynnosc c : p.getCzynnoscList()) {
                if(z.getId()==c.getIdZadanie().getId()) {
                    int ilep = c.getPracownikList().size();
                    sp.setCzas(sp.getCzas() + (double)c.getCzasTrwania()/(double)ilep);
                    sp.setKoszt(sp.getKoszt() + (double)c.getCzasTrwania()/60.0*p.getStawka()/(double)ilep);
                    
                }
            }
            lsp.add(sp);
        }
        return lsp;
    }
    
    public List<StatystykaSprzetu> statystykaSprzetu(Zadanie z) {
        ArrayList<StatystykaSprzetu> lsp = new ArrayList<>();
        for(Czynnosc c : z.getCzynnoscList()) {
            StatystykaSprzetu sp = new StatystykaSprzetu();
            sp.setCzynnosc(c);
            sp.setCzas(c.getCzasTrwania());
            sp.setKoszt(c.getCzasTrwania()/60.0*c.getStawka());
            lsp.add(sp);
        }
        return lsp;
    }
    
    public double kosztZadania(Zadanie zadanie) {
        double koszt = 0;
        for(Czynnosc c : zadanie.getCzynnoscList()) {
            koszt+=this.kosztCzynnosci(c);
        }
        return koszt;
    }
    
    public double kosztWieluZadan(List<Zadanie> zadania) {
        double koszt = 0;
        for(Zadanie z : zadania) {
            koszt+=this.kosztZadania(z);
        }
        return koszt;
    }
    
    public double kosztCzynnosci(Czynnosc c) {
        double koszt = 0;
        
        int ilePrac = c.getPracownikList().size();
        if(ilePrac==0)
            return 0.0;
        koszt+=c.getStawka()*c.getCzasTrwania()/60.0;
        for(Pracownik p : c.getPracownikList()) {
            koszt+=this.kosztPracownika(p, (double)c.getCzasTrwania()/(double)ilePrac);
        }
        return koszt;
    }
    
    public double kosztPracownika(Pracownik p, double czas) {
        return p.getStawka()*czas;
    }
    
    public double sredniaStawkaPracownika(Zadanie z) {
        double srednia = 0.0;
        List<StatystykaPracownika> lsp = this.statystykaPracownika(z);
        for(StatystykaPracownika sp : lsp) {
            srednia += sp.getKoszt();
        }
        srednia/=(double)lsp.size();
        return srednia;
    }
    
    public double sredniKosztCzynnosci(Zadanie z) {
        double srednia = 0.0;
        List<StatystykaSprzetu> lsp = this.statystykaSprzetu(z);
        for(StatystykaSprzetu sp : lsp) {
            srednia += sp.getKoszt();
        }
        srednia/=(double)lsp.size();
        return srednia;
    }
    
    public String statusZadania(Zadanie z) {
        if(z.getStatus()==0) {
            return "Oczekuje na wykonanie";
        } else if(z.getStatus()==1) {
            return "W trakcie wykonania";
        } else {
            return "Zakonczone";
        }
    }
    
    public void zatwierdzZadanie(Zadanie z) {
        if(z.getStatus()==2) {
            db.removeZadanie(z.getId());
        }
    }
    
}

web/klient/add_czynnosc_zadanie.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type" />
                <title>Widok</title>
            </f:facet>
            <f:metadata>
                <f:viewParam name="zadid" value="#{controlCzynnosc.idZadanie}"/>

            </f:metadata>
        </h:head>
        <h:body>
<!--            <ui:include src="navbar.xhtml"/>-->

            <h:form id="formularz">
                <p:dataTable id="tabela" value="#{controlCzynnosc.czynnoscList}" var="Czynnosc">
                    <f:facet name="header">
                        Czynnosci
                    </f:facet>
                    <p:column headerText="Id">
                        <h:outputText value="#{Czynnosc.id}" />
                    </p:column>

                    <p:column headerText="Nazwa">
                        <h:outputText value="#{Czynnosc.nazwa}" />
                    </p:column>

                    <p:column headerText="Stawka">
                        <h:outputText value="#{Czynnosc.stawka}" />
                    </p:column>

                    <p:column headerText="Czas trwania">
                        <h:outputText value="#{Czynnosc.czasTrwania}" />
                    </p:column>

                    <p:column headerText="Usun">
                        <p:commandButton action="#{controlCzynnosc.deleteCzynnosc(Czynnosc)}" update=" tabela" value="Usun"/>
                    </p:column>

                </p:dataTable>

                <span>
                    <p:outputLabel value="Nazwa: "/>
                    <p:inputText value="#{controlCzynnosc.tmpczynnoscNazwa}"/>
                </span>
                <span>
                    <p:outputLabel value="Stawka: "/>
                    <p:inputText value="#{controlCzynnosc.tmpczynnoscStawka}"/>
                </span>
                <span>
                    <p:outputLabel value="Czas trwania: "/>
                    <p:inputText value="#{controlCzynnosc.tmpczynnoscCzasTrwania}"/>
                </span>


                <div>
                    <p:commandButton value="Sprawdz pracownikow" action="#{controlCzynnosc.checkPracownik}" update="tabela listaprac"/>
                    <p:commandButton value="Dodaj czynnosc" action="#{controlCzynnosc.addCzynnosc}" update="tabela listaprac"/>
                </div>
                <p:pickList id="listaprac" 
                            value="#{controlCzynnosc.pracownicy}" 
                        var="Pracownik" 
                        converter="entityConverter"
                        itemLabel="#{controlCzynnosc.nazwaPracownik(Pracownik)}" 
                        itemValue="#{Pracownik}"
                         />
            </h:form>
        </h:body>
    </f:view>
</html>

web/klient/add_zadanie.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type" />
                <title>Dodaj zastosowanie</title>
            </f:facet>
        </h:head>
        <h:body>
<!--            <ui:include src="navbar.xhtml"/>-->
            
            
            <h:form id="formulaz">
                <div><p:outputLabel>DODAJ NOWE ZADANIE</p:outputLabel></div>
                <p:growl id="growl" life="2000" />
                <div>
                    <p:outputLabel value="Nazwa: "/>
                    <p:inputText value="#{addZadanie.nazwa}"/>
                </div>
                
                <p:outputLabel for="popup" value="Czas rozpoczecia:" />
                <p:calendar id="popup" value="#{addZadanie.czasRozpoczecia}" pattern="MM/dd/yyyy HH:mm:ss" />

                <div>
                    <p:commandButton value="Dodaj Zadanie" action="#{addZadanie.dodajZadanieKlientowi()}"/>
                </div>
                <div>
                    <p:button value="Widok zadan" outcome="widok_zadania" />
                </div>

            </h:form>
        </h:body>
    </f:view>
</html>

web/klient/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <head>
        <title>TODO supply a title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <h:body>
        <h1>Hello klient</h1>
        <br />
        <h:link outcome="/index" value="Back to Homepage" />
    </h:body>
</html>

web/klient/widok_wiadomosci.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view>
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type" />
                <title>Twoj Widok</title>
            </f:facet>
            <style>
                .nieprzeczytana{
                    background-color: greenyellow;
                }
            </style>
        </h:head>
        <h:body>
            <h:form id="formOdebrane">
                <p:dataTable id="tabela" 
                             value="#{controlWiadomosc.wiadomosci}" 
                             var="Wiadomosc" rowStyleClass="#{Wiadomosc.przeczytana lt 1 ? 'nieprzeczytana' : null}" >

                    <f:facet name="header">
                        Odebrane
                    </f:facet>
                    <p:column headerText="Nadawca" >
                        <h:outputText value="#{Wiadomosc.nadawca.username}" />
                    </p:column>

                    <p:column headerText="Temat">
                        <h:outputText value="#{Wiadomosc.tytul}" />
                    </p:column>

                    <p:column headerText="Data wyslania">
                        <h:outputText value="#{Wiadomosc.dataWyslania}" />
                    </p:column>
                    <p:column headerText="Odczytaj">
                        <p:commandButton action="#{controlWiadomosc.odczytaj(Wiadomosc)}" value="odczytaj" update="@form" />
                    </p:column>

                </p:dataTable>
                <p:commandButton value="Nowa" oncomplete="PF('dlg').show()" icon="ui-icon-disk" />

                <p:dialog header="Content" widgetVar="dlg" showEffect="fade" hideEffect="fade">
                    <p:selectOneMenu id="car" value="#{controlWiadomosc.odbiorca}">
                        <f:selectItems value="#{controlWiadomosc.uzytkownicy}" var="Odbiorca" itemLabel="#{Odbiorca.username}" itemValue="#{Odbiorca.username}"/>
                    </p:selectOneMenu>
                    <p:inputText value="#{controlWiadomosc.tytul}" />
                    <p:editor id="editor" widgetVar="editorWidget" value="#{controlWiadomosc.wiadomosc}" width="600" />
                    <p:commandButton value="wyslij" action="#{controlWiadomosc.wyslij()}" update=":formOdebrane:tabela" />
                </p:dialog>

                <p:dialog header="Content" widgetVar="dlg_read" showEffect="fade" hideEffect="fade">
                    <p:scrollPanel mode="native" >
                        <h:outputText value="#{controlWiadomosc.wybranaWiadomosc.tresc}" escape="falsse" />
                    </p:scrollPanel>
                </p:dialog>
            </h:form>
        </h:body>
    </f:view>

</html>

web/klient/widok_zadania.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view>
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type" />
                <title>Twoj Widok</title>
            </f:facet>
        </h:head>
        <h:body>
<!--            <ui:include src="navbar.xhtml"/>-->
            <!--<div>Tutaj bedzie program</div>-->
            <h:form id="formZadania">
                <!--<p:panel header="Pracownicy">-->
                <p:dataTable id="tabela" 
                             value="#{controlZadanie.zadaniaKlienta}" 
                             var="Zadanie" 
                             selectionMode="multiple"

                             selection="#{controlZadanie.wybraneZadania}"  rowKey="#{Zadanie.id}">
                    <p:ajax event="toggleSelect" process="@this" update="pods"/>
                    <p:ajax event="rowSelect" process="@this" update="pods"/>
                    <p:ajax event="rowUnselect" process="@this" update="pods"/>
                    <f:facet name="header">
                        Zadania
                    </f:facet>
                    <p:column style="width:16px">
                        <p:rowToggler />
                    </p:column>
                    <p:column headerText="Id" >
                        <!--<f:facet name="header"><h:outputLabel value="Id"/></f:facet>-->
                        <h:outputText value="#{Zadanie.id}" />
                    </p:column>

                    <p:column headerText="Nazwa">
                        <!--<f:facet name="header"><h:outputLabel value="Imie"/></f:facet>-->
                        <h:outputText value="#{Zadanie.nazwa}" />
                    </p:column>

                    <p:column headerText="Data rozpoczecia">
                        <!--<f:facet name="header"><h:outputLabel value="Imie"/></f:facet>-->
                        <h:outputText value="#{Zadanie.czasRozpoczecia}" />
                    </p:column>

                    <p:column headerText="Data zakonczenia">
                        <!--<f:facet name="header"><h:outputLabel value="Imie"/></f:facet>-->
                        <h:outputText value="#{controlZadanie.dataZakonczeniaZadania(Zadanie)}" />
                    </p:column>
                    <p:column headerText="Koszt">
                        <!--<f:facet name="header"><h:outputLabel value="Imie"/></f:facet>-->
                        <h:outputText value="#{controlZadanie.kosztZadania(Zadanie)}" />
                    </p:column>
                    <p:column headerText="Status">
                        <h:outputText value="#{controlZadanie.statusZadania(Zadanie)}" />
                    </p:column>

                    <p:column style="text-align: center" headerText="Inne">
                        <p:commandButton action="#{controlZadanie.deleteZadanie(Zadanie)}" update="@form" icon="ui-icon-trash"/>
                        <p:button outcome="add_czynnosc_zadanie" value="Zarzadzaj czynnosciami">
                            <f:param name="zadid" value ="#{Zadanie.id}"/>
                            <f:param name="i" value="-1"/>
                        </p:button>
                    </p:column>

                    <f:facet name="footer">
                        <h:panelGroup layout="block" id="pods">
                            <h:outputText value="Koszt wybranych zadan: " />
                            <h:outputText value="#{controlZadanie.kosztWieluZadan(controlZadanie.wybraneZadania)}" />
                        </h:panelGroup>
                    </f:facet>

                    <p:rowExpansion>
                        <p:dataTable 
                            value="#{controlZadanie.statystykaPracownika(Zadanie)}" 
                            var="Stat" style="width:500px">
                            <f:facet name="header">
                                pracownicy
                            </f:facet>
                            <p:column headerText="Imie">
                                <h:outputText value="#{Stat.pracownik.imie}" />
                            </p:column>
                            <p:column headerText="Nazwisko">
                                <h:outputText value="#{Stat.pracownik.nazwisko}" />
                            </p:column>
                            <p:column headerText="Czas pracy">
                                <h:outputText value="#{Stat.czas}" />
                            </p:column>
                            <p:column headerText="Koszt">
                                <h:outputText value="#{Stat.koszt}" />
                            </p:column>
                        </p:dataTable>

                        <p:dataTable 
                            value="#{controlZadanie.statystykaSprzetu(Zadanie)}" 
                            var="Stat" style="width:500px">
                            <f:facet name="header">
                                Sprzet
                            </f:facet>
                            <p:column headerText="Nazwa">
                                <h:outputText value="#{Stat.czynnosc.nazwa}" />
                            </p:column>
                            <p:column headerText="Czas pracy">
                                <h:outputText value="#{Stat.czas}" />
                            </p:column>
                            <p:column headerText="Koszt">
                                <h:outputText value="#{Stat.koszt}" />
                            </p:column>
                        </p:dataTable>

                        <p:panelGrid columns="2" style="width:500px">
                            <f:facet name="header">
                                <h:outputText value="Srednie:" />
                            </f:facet>

                            <h:outputText value="Pracownika:" />
                            <h:outputText value="#{controlZadanie.sredniaStawkaPracownika(Zadanie)}" />

                            <h:outputText value="Sprzetu:" />
                            <h:outputText value="#{controlZadanie.sredniKosztCzynnosci(Zadanie)}" />
                        </p:panelGrid>

                    </p:rowExpansion>


                </p:dataTable>
                <p:button value="Dodaj" outcome="add_zadanie"/>
                <p:button value="Wiadomosci" outcome="widok_wiadomosci"/>
                <p:commandButton action="#{logout.logout()}" value="Wyloguj"/>

                <!--</p:panel>-->
                <br/>
                <!--                <div>
                                    <p:commandButton value="Dodaj pracownika" action="addprac"/>
                                </div>-->
            </h:form>
        </h:body>
    </f:view>

</html>