src/java/control/AddZadanieBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package control;

import ejb.DataBean;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import model.Czynnosc;
import model.Pracownik;
import org.primefaces.model.DualListModel;

/**
 *
 * @author Piotrek
 */
@ManagedBean(name = "addZadanie")
@ViewScoped
public class AddZadanieBean {

    private static Logger logger = Logger.getLogger(".controll.AddZadanieBean");
    
    private String Nazwa;
    private List<Czynnosc> czynnosci = new ArrayList<Czynnosc>();
    private DualListModel<Pracownik> pracownicy;
    private Date czasRozpoczecia;
    
    private String tmpczynnoscNazwa;
    private Double tmpczynnoscStawka;
    private int tmpczynnoscCzasTrwania;
    
    @EJB
    private DataBean db;

    /**
     * Creates a new instance of AddZadanieBean
     */
    public AddZadanieBean() {
    }

    public String getNazwa() {
        return Nazwa;
    }

    public void setNazwa(String Nazwa) {
        this.Nazwa = Nazwa;
    }

    public List<Czynnosc> getCzynnosci() {
        return czynnosci;
    }

    public void setCzynnosci(List<Czynnosc> czynnosci) {
        this.czynnosci = czynnosci;
    }



    public void setPracownicy(DualListModel<Pracownik> pracownicy) {
        this.pracownicy = pracownicy;
    }

    public String getTmpczynnoscNazwa() {
        return tmpczynnoscNazwa;
    }

    public void setTmpczynnoscNazwa(String tmpczynnoscNazwa) {
        this.tmpczynnoscNazwa = tmpczynnoscNazwa;
    }

    public Double getTmpczynnoscStawka() {
        return tmpczynnoscStawka;
    }

    public void setTmpczynnoscStawka(Double tmpczynnoscStawka) {
        this.tmpczynnoscStawka = tmpczynnoscStawka;
    }

    public int getTmpczynnoscCzasTrwania() {
        return tmpczynnoscCzasTrwania;
    }

    public void setTmpczynnoscCzasTrwania(int tmpczynnoscCzasTrwania) {
        this.tmpczynnoscCzasTrwania = tmpczynnoscCzasTrwania;
    }
    
    
    
    

    public Date getCzasRozpoczecia() {
        return czasRozpoczecia;
    }

    public void setCzasRozpoczecia(Date czasRozpoczecia) {
        this.czasRozpoczecia = czasRozpoczecia;
    }
    
    public void dodajZadanie() {
        db.addZadanie(this.Nazwa, this.czasRozpoczecia);
    }
    
    public void dodajZadanieKlientowi() {
        String username = FacesContext.getCurrentInstance().getExternalContext().getUserPrincipal().getName();
        db.addZadanieKlientowi(this.Nazwa,this.czasRozpoczecia,username);
    }
    

    
}

src/java/control/AddZastosowanieBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package control;

import ejb.DataBean;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

/**
 *
 * @author Piotrek
 */
@ManagedBean(name = "addZastosowanie")
@RequestScoped
public class AddZastosowanieBean {
    
    private static Logger logger = Logger.getLogger(".controll.AddZastosowanieBean");
    
    private String nazwaNewZastosowanie;

    @EJB
    private DataBean db;

    /**
     * Creates a new instance of AddZastosowanieBean
     */
    public AddZastosowanieBean() {
    }

    /**
     * @return the nazwaNewZastosowanie
     */
    public String getNazwaNewZastosowanie() {
        return nazwaNewZastosowanie;
    }

    /**
     * @param nazwaNewZastosowanie the nazwaNewZastosowanie to set
     */
    public void setNazwaNewZastosowanie(String nazwaNewZastosowanie) {
        this.nazwaNewZastosowanie = nazwaNewZastosowanie;
    }
    
    public void addNewZastosowanie() {
        try {
            db.addZastosowanie(nazwaNewZastosowanie);
            this.addMessage("Dodano przedmiot: " + nazwaNewZastosowanie);
            this.nazwaNewZastosowanie = "";

        } catch (Exception e) {
            logger.warning(e.getMessage());
            e.printStackTrace();
        }
    }

    public void addMessage(String summary) {
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, summary, null);
        FacesContext.getCurrentInstance().addMessage(null, message);
    }
    
}

src/java/control/ControlPrzedmiotBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package control;

import ejb.DataBean;
import java.util.List;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import model.Przedmiot;

/**
 *
 * @author Piotrek
 */
@ManagedBean(name = "controlPrzedmiot")
@RequestScoped
public class ControlPrzedmiotBean {

    /**
     * Creates a new instance of ControlPrzedmiotBean
     */
    private static Logger logger = Logger.getLogger(".control.ControlPrzedmiotBean");

    @EJB
    private DataBean db;
    
    private List<Przedmiot> Przedmioty;

    public ControlPrzedmiotBean() {
    }

    public List<Przedmiot> getPrzedmioty() {
        try {
            this.Przedmioty = db.getPrzedmioty();
        } catch (Exception e) {
            logger.warning(("nieudalo sie pobrac przedmiotow"));
            e.printStackTrace();
        }
        return Przedmioty;
    }

    public String ownerName(Przedmiot przedmiot) {
        if (przedmiot.getIdPracownik() != null) {
            return przedmiot.getIdPracownik().getImie() + " " + przedmiot.getIdPracownik().getNazwisko();
        }
        return "";
    }

}

web/add_przedmiot_prac.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type" />
                <title>Widok</title>
            </f:facet>
            <f:metadata>
                <f:viewParam name="pracid" value="#{AddPrzedmiotForPracownik.pracownikID}"/>
                
            </f:metadata>
        </h:head>
        <h:body>
            <ui:include src="navbar.xhtml"/>

            <h:form>
            <p:pickList id="pickList" 
                        value="#{AddPrzedmiotForPracownik.przedmioty}" 
                        var="przedmiot" 
                        converter="entityConverter"
                        itemLabel="#{przedmiot.nazwa}" 
                        itemValue="#{przedmiot}"
                         />

            <p:commandLink id="add_items" value="Submit" action="#{AddPrzedmiotForPracownik.addPrzedmioty()}" update="" style="margin-top:5px" >
                <f:param name="pracid" value ="#{AddPrzedmiotForPracownik.pracownikID}"/>
            </p:commandLink>
            </h:form>
        </h:body>
    </f:view>
</html>

web/add_zadanie.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type" />
                <title>Dodaj zastosowanie</title>
            </f:facet>
        </h:head>
        <h:body>
            <ui:include src="navbar.xhtml"/>
            
            
            <h:form id="formulaz">
                <div><p:outputLabel>DODAJ NOWE ZADANIE</p:outputLabel></div>
                <p:growl id="growl" life="2000" />
                <div>
                    <p:outputLabel value="Nazwa: "/>
                    <p:inputText value="#{addZadanie.nazwa}"/>
                </div>
                
                <p:outputLabel for="popup" value="Czas rozpoczecia:" />
                <p:calendar id="popup" value="#{addZadanie.czasRozpoczecia}" pattern="MM/dd/yyyy HH:mm:ss" />

                <div>
                    <p:commandButton value="Dodaj Zadanie" action="#{addZadanie.dodajZadanie()}"/>
                </div>

            </h:form>
        </h:body>
    </f:view>
</html>

web/add_zastosowania_przedmiotu_pracownika.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type" />
                <title>Widok</title>
            </f:facet>
            <f:metadata>
                <f:viewParam name="przedid" value="#{addZastosowanieForPrzedmiot.przedmiotID}"/>
                
            </f:metadata>
        </h:head>
        <h:body>
            <ui:include src="navbar.xhtml"/>

            <h:form>
            <p:pickList id="pickList" 
                        value="#{addZastosowanieForPrzedmiot.zastosowania}" 
                        var="Zastosowanie" 
                        converter="entityConverter"
                        itemLabel="#{Zastosowanie.nazwa}" 
                        itemValue="#{Zastosowanie}"
                         />

            <p:commandLink id="add_items" value="Submit" action="#{addZastosowanieForPrzedmiot.add_zastosowania()}" update="" style="margin-top:5px" >
                <f:param name="przedid" value ="#{addZastosowanieForPrzedmiot.przedmiotID}"/>
            </p:commandLink>
            </h:form>
        </h:body>
    </f:view>
</html>

web/add_zastosowanie.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type" />
                <title>Dodaj zastosowanie</title>
            </f:facet>
        </h:head>
        <h:body>
            <ui:include src="navbar.xhtml"/>
            
            
            <h:form>
                <div><p:outputLabel>DODAJ NOWE ZASTOSOWANIE</p:outputLabel></div>
                <p:growl id="growl" life="2000" />
                <div>
                    <p:outputLabel value="Nazwa: "/>
                    <p:inputText value="#{addZastosowanie.nazwaNewZastosowanie}"/>
                </div>
                <div>
                    <p:commandButton value="Dodaj" action="#{addZastosowanie.addNewZastosowanie}" update="@form"/>
                </div>
<!--                <div>
                    <p:commandButton value="Lista przedmiotów" action="widok_przedmioty"/>
                </div>-->
            </h:form>
        </h:body>
    </f:view>
</html>

web/login.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view>
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type" />
                <title>Login</title>
            </f:facet>
        </h:head>

        <h:body>
            <p:panel header="Login From">
                <form method="POST" action="j_security_check">
                    Username: <input type="text" name="j_username" />
                    Password: <input type="password" name="j_password" />
                    <br />
                    <input type="submit" value="Login" />
                    <input type="reset" value="Reset" />
                </form>
            </p:panel>
        </h:body>
    </f:view>

</html>

web/przedmioty_pracownika.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view>
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type" />
                <title>Twoj Widok</title>
            </f:facet>
        </h:head>
            <f:metadata>
                <f:viewParam name="pracid" value="#{controlPrzedmiotyPracownika.pracownikID}"/>
                <f:event type="preRenderView" listener="#{controlPrzedmiotyPracownika.loadData}"/>
            </f:metadata>
        <h:body>
            <!--<div>Tutaj bedzie program</div>-->
            <ui:include src="navbar.xhtml"/>
      
            <h:form id="formPrzedmiotyPracownika">
                <!--<p:panel header="Pracownicy">-->
                <p:dataTable id="tabela" value="#{controlPrzedmiotyPracownika.getPrzedmiotyPracownika()}" var="Przedmiot">
                    <f:facet name="header">
                        Przedmioty pracownika #{controlPrzedmiotyPracownika.imiePracownika()}
                    </f:facet>
                    <p:column headerText="Id">
                        <!--<f:facet name="header"><h:outputLabel value="Id"/></f:facet>-->
                        <h:outputText value="#{Przedmiot.id}" />
                    </p:column>

                    <p:column headerText="Nazwa">
                        <!--<f:facet name="header"><h:outputLabel value="Imie"/></f:facet>-->
                        <h:outputText value="#{Przedmiot.nazwa}" />
                    </p:column>



                    <p:column style="text-align: center" headerText="Inne">
                        <f:facet name="header"><h:outputLabel value="Inne"/></f:facet>
                        <h:commandLink action="#{controlPrzedmiotyPracownika.deletePrzedmiotPracownika(Przedmiot)}"
                                         value="usun">
                            <f:param name="pracid" value ="#{controlPrzedmiotyPracownika.pracownikID}"/>
                            <!--<f:setPropertyActionListener target="#{controlPrzedmiotyPracownika.pracownikID}" value="#{controlPrzedmiotyPracownika.pracownikID}"/>-->
                            <f:attribute name="test" value="test"/>
                            <f:param name="i" value="-1"/>
                        </h:commandLink>
                        <br/>
                        
                       <p:button outcome="zastosowania_przedmiotu_pracownika" value="Wyświetl zastosowania">
                            <f:param name="pracid" value ="#{controlPrzedmiotyPracownika.pracownikID}"/>
                            <f:param name="przedid" value ="#{Przedmiot.id}"/>
                            <f:param name="i" value="-1"/>
                        </p:button>
                        <p:button outcome="add_zastosowania_przedmiotu_pracownika" value="Dodaj zastosowania">
                            <f:param name="pracid" value ="#{controlPrzedmiotyPracownika.pracownikID}"/>
                            <f:param name="przedid" value ="#{Przedmiot.id}"/>
                            <f:param name="i" value="-1"/>
                        </p:button>
                    </p:column>
                </p:dataTable>

                <!--</p:panel>-->
                <br/>
            </h:form>
        </h:body>
    </f:view>

</html>

web/widok_przedmioty.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view>
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type" />
                <title>Przedmioty</title>
            </f:facet>
        </h:head>
        <h:body>
            <ui:include src="navbar.xhtml"/>
            <!--<div>Przedmioty</div>-->
            <h:form id="formPrzedmioty">
                <!--<p:panel header="Pracownicy">-->
                <p:dataTable id="tabela" value="#{controlPrzedmiot.przedmioty}" var="Przedmiot">
                    <f:facet name="header">
                        Przedmioty
                    </f:facet>
                    <p:column headerText="Id">
                        <!--<f:facet name="header"><h:outputLabel value="Id"/></f:facet>-->
                        <h:outputText value="#{Przedmiot.id}" />
                    </p:column>

                    <p:column headerText="Nazwa">
                        <!--<f:facet name="header"><h:outputLabel value="Imie"/></f:facet>-->
                        <h:outputText value="#{Przedmiot.nazwa}" />
                    </p:column>
                    
                    <p:column headerText="Właściciel">
                        <!--<f:facet name="header"><h:outputLabel value="Imie"/></f:facet>-->
                        <h:outputText value="#{controlPrzedmiot.ownerName(Przedmiot)}" />
                    </p:column>



                    <p:column style="width:64px;text-align: center" headerText="Inne">
                        <f:facet name="header"><h:outputLabel value="Inne"/></f:facet>
                        <p:commandButton action="#{deletePrzedmiot.deletePrzedmiot(Przedmiot)}" update="@form" icon="ui-icon-trash"/>
                    </p:column>
                </p:dataTable>

                <!--</p:panel>-->
                <br/>
<!--                <div>
                    <p:commandButton value="Dodaj przedmiot" action="addprzed"/>
                </div>-->
            </h:form>
        </h:body>
    </f:view>

</html>

web/widok_zadania.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view>
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type" />
                <title>Twoj Widok</title>
            </f:facet>
        </h:head>
        <h:body>
            <ui:include src="navbar.xhtml"/>
            <!--<div>Tutaj bedzie program</div>-->
            <h:form id="formZadania">
                <!--<p:panel header="Pracownicy">-->
                <p:dataTable id="tabela" 
                             value="#{controlZadanie.zadania}" 
                             var="Zadanie" 
                             selectionMode="multiple"

                             selection="#{controlZadanie.wybraneZadania}"  rowKey="#{Zadanie.id}">
                    <p:ajax event="toggleSelect" process="@this" update="pods"/>
                    <p:ajax event="rowSelect" process="@this" update="pods"/>
                    <p:ajax event="rowUnselect" process="@this" update="pods"/>
                    <f:facet name="header">
                        Zadania
                    </f:facet>
                    <p:column style="width:16px">
                        <p:rowToggler />
                    </p:column>
                    <p:column headerText="Id" >
                        <!--<f:facet name="header"><h:outputLabel value="Id"/></f:facet>-->
                        <h:outputText value="#{Zadanie.id}" />
                    </p:column>

                    <p:column headerText="Nazwa">
                        <!--<f:facet name="header"><h:outputLabel value="Imie"/></f:facet>-->
                        <h:outputText value="#{Zadanie.nazwa}" />
                    </p:column>

                    <p:column headerText="Data rozpoczecia">
                        <!--<f:facet name="header"><h:outputLabel value="Imie"/></f:facet>-->
                        <h:outputText value="#{Zadanie.czasRozpoczecia}" />
                    </p:column>

                    <p:column headerText="Data zakonczenia">
                        <!--<f:facet name="header"><h:outputLabel value="Imie"/></f:facet>-->
                        <h:outputText value="#{controlZadanie.dataZakonczeniaZadania(Zadanie)}" />
                    </p:column>
                    <p:column headerText="Koszt">
                        <!--<f:facet name="header"><h:outputLabel value="Imie"/></f:facet>-->
                        <h:outputText value="#{controlZadanie.kosztZadania(Zadanie)}" />
                    </p:column>

                    <p:column style="text-align: center" headerText="Inne">
                        <p:commandButton action="#{controlZadanie.deleteZadanie(Zadanie)}" update="@form" icon="ui-icon-trash"/>
                        <p:button outcome="add_czynnosc_zadanie" value="Zarzadzaj czynnosciami">
                            <f:param name="zadid" value ="#{Zadanie.id}"/>
                            <f:param name="i" value="-1"/>
                        </p:button>
                    </p:column>

                    <f:facet name="footer">
                        <h:panelGroup layout="block" id="pods">
                            <h:outputText value="Koszt wybranych zadan: " />
                            <h:outputText value="#{controlZadanie.kosztWieluZadan(controlZadanie.wybraneZadania)}" />
                        </h:panelGroup>
                    </f:facet>

                    <p:rowExpansion>
                        <p:dataTable 
                            value="#{controlZadanie.statystykaPracownika(Zadanie)}" 
                            var="Stat" style="width:500px">
                            <f:facet name="header">
                                pracownicy
                            </f:facet>
                            <p:column headerText="Imie">
                                <h:outputText value="#{Stat.pracownik.imie}" />
                            </p:column>
                            <p:column headerText="Nazwisko">
                                <h:outputText value="#{Stat.pracownik.nazwisko}" />
                            </p:column>
                            <p:column headerText="Czas pracy">
                                <h:outputText value="#{Stat.czas}" />
                            </p:column>
                            <p:column headerText="Koszt">
                                <h:outputText value="#{Stat.koszt}" />
                            </p:column>
                        </p:dataTable>

                        <p:dataTable 
                            value="#{controlZadanie.statystykaSprzetu(Zadanie)}" 
                            var="Stat" style="width:500px">
                            <f:facet name="header">
                                Sprzet
                            </f:facet>
                            <p:column headerText="Nazwa">
                                <h:outputText value="#{Stat.czynnosc.nazwa}" />
                            </p:column>
                            <p:column headerText="Czas pracy">
                                <h:outputText value="#{Stat.czas}" />
                            </p:column>
                            <p:column headerText="Koszt">
                                <h:outputText value="#{Stat.koszt}" />
                            </p:column>
                        </p:dataTable>

                        <p:panelGrid columns="2" style="width:500px">
                            <f:facet name="header">
                                <h:outputText value="Srednie:" />
                            </f:facet>

                            <h:outputText value="Pracownika:" />
                            <h:outputText value="#{controlZadanie.sredniaStawkaPracownika(Zadanie)}" />

                            <h:outputText value="Sprzetu:" />
                            <h:outputText value="#{controlZadanie.sredniKosztCzynnosci(Zadanie)}" />
                        </p:panelGrid>

                    </p:rowExpansion>


                </p:dataTable>

                <!--</p:panel>-->
                <br/>
                <!--                <div>
                                    <p:commandButton value="Dodaj pracownika" action="addprac"/>
                                </div>-->
            </h:form>
        </h:body>
    </f:view>

</html>

web/zastosowania_przedmiotu_pracownika.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view>
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type" />
                <title>Zastosowania przedmiotu pracownika</title>
            </f:facet>
        </h:head>
            <f:metadata>
                <f:viewParam name="pracid" value="#{controlZastosowaniaPrzedmiotuPracownika.pracownikID}"/>
                <f:viewParam name="przedid" value="#{controlZastosowaniaPrzedmiotuPracownika.przedmiotID}"/>
                
            </f:metadata>
        <h:body>
            <!--<div>Tutaj bedzie program</div>-->
            <ui:include src="navbar.xhtml"/>
      
            <h:form id="formZastosowaniaPrzedmiotuPracownika">
                <!--<p:panel header="Pracownicy">-->
                <p:dataTable id="tabela" value="#{controlZastosowaniaPrzedmiotuPracownika.zastosowania}" var="Zastosowanie">
                    <f:facet name="header">
                        Zastosowania przedmiotu #{controlZastosowaniaPrzedmiotuPracownika.przedmiot.nazwa} nalezacego do #{controlZastosowaniaPrzedmiotuPracownika.imiePracownika()}
                    </f:facet>
                    <p:column headerText="Id">
                        <!--<f:facet name="header"><h:outputLabel value="Id"/></f:facet>-->
                        <h:outputText value="#{Zastosowanie.id}" />
                    </p:column>

                    <p:column headerText="Nazwa">
                        <!--<f:facet name="header"><h:outputLabel value="Imie"/></f:facet>-->
                        <h:outputText value="#{Zastosowanie.nazwa}" />
                    </p:column>



                    <p:column style="text-align: center" headerText="Inne">
                        <f:facet name="header"><h:outputLabel value="Inne"/></f:facet>
                        <h:commandLink action="#{controlZastosowaniaPrzedmiotuPracownika.deleteZastosowanie(Zastosowanie)}"
                                         value="usun">
                            
                        </h:commandLink>
                        
                      
                    </p:column>
                </p:dataTable>

                <!--</p:panel>-->
                <br/>
            </h:form>
        </h:body>
    </f:view>

</html>